import "./globals.css";
import { FavoritesProvider } from "./context/FavoritesContext";
import Sidebar from "@/app/components/sidebar";
import { Playfair_Display } from "next/font/google";

const playfair = Playfair_Display({
  variable: "--font-playfair",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`min-h-full flex flex-col ${playfair.variable} antialiased`}>
        <FavoritesProvider>
          <div>
            <Sidebar />
            <div className="md:ml-64 flex-1">{children}</div>
          </div>
        </FavoritesProvider>
      </body>
    </html>
  );
}
